In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [9]:
df=pd.read_csv("/content/gdrive/MyDrive/spam.csv",encoding = "ISO-8859-1")

In [10]:
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB


In [15]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [27]:
df['v1']=le.fit_transform(df['v1'])
df['v2']=le.fit_transform(df['v2'])

In [28]:
df.head()

v1    v2 Unnamed: 2 Unnamed: 3 Unnamed: 4
0   0  1079        NaN        NaN        NaN
1   0  3101        NaN        NaN        NaN
2   1  1000        NaN        NaN        NaN
3   0  4088        NaN        NaN        NaN
4   0  2757        NaN        NaN        NaN

In [29]:
train_set = df.iloc[:,1:2].values

In [30]:
train_set

array([[1079],
       [3101],
       [1000],
       ...,
       [3286],
       [3901],
       [3409]])

In [31]:
from sklearn.preprocessing import MinMaxScaler

sc = MinMaxScaler()
scaled_tr = sc.fit_transform(train_set)

In [32]:
scaled_tr[60-60:60,0]

array([0.20878483, 0.6000387 , 0.19349845, 0.79102167, 0.53347523,
       0.19543344, 0.17705108, 0.07120743, 0.82217492, 0.23916409,
       0.40363777, 0.66505418, 0.80205108, 0.41679567, 0.32585139,
       0.88815789, 0.58301084, 0.17221362, 0.187113  , 0.17356811,
       0.4369195 , 0.45239938, 0.69736842, 0.02883127, 0.18556502,
       0.46091331, 0.50174149, 0.14125387, 0.3999613 , 0.03037926,
       0.8246904 , 0.90073529, 0.47155573, 0.18866099, 0.73935759,
       0.95859133, 0.625387  , 0.37287152, 0.05824303, 0.26354489,
       0.64202786, 0.13893189, 0.00890093, 0.82082043, 0.22581269,
       0.54256966, 0.14299536, 0.18401703, 0.90092879, 0.79063467,
       0.86339009, 0.02341331, 0.46962074, 0.88660991, 0.66679567,
       0.14821981, 0.11648607, 0.71033282, 0.73006966, 0.91795666])

In [33]:
x_train=[]
y_train=[]

for i in range(60,1258):
  x_train.append(scaled_tr[i-60:i,0])
  y_train.append(scaled_tr[i,0])

In [34]:
import numpy as np
x_train,y_train = np.array(x_train),np.array(y_train)

In [35]:
x_train.shape

(1198, 60)

In [36]:
x_train = np.reshape(x_train,(1198, 60, 1))

In [37]:
x_train.shape

(1198, 60, 1)

In [38]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,Dense

In [39]:
model = Sequential()
model.add(LSTM(50,input_shape=(x_train.shape[1],1),return_sequences=True))
model.add(LSTM(50,return_sequences=True))
model.add(LSTM(50,return_sequences=True))
model.add(LSTM(50))
model.add(Dense(1))

In [40]:
model.compile(optimizer='adam',loss='mse')

In [41]:
model.fit(x_train,y_train,epochs=5,batch_size=32)

Epoch 1/5
38/38 [==============================] - 12s 113ms/step - loss: 0.1070
Epoch 2/5
38/38 [==============================] - 4s 111ms/step - loss: 0.0887
Epoch 3/5
38/38 [==============================] - 4s 110ms/step - loss: 0.0877
Epoch 4/5
38/38 [==============================] - 4s 117ms/step - loss: 0.0904
Epoch 5/5
38/38 [==============================] - 4s 112ms/step - loss: 0.0881


In [42]:
model.save('lstm.h5')

In [43]:
x_train[100].shape

(60, 1)

In [44]:
y_pred = model.predict(x_train)
y_pred

38/38 [==============================] - 3s 31ms/step


array([[0.49227685],
       [0.49445352],
       [0.49694672],
       ...,
       [0.4974522 ],
       [0.4983847 ],
       [0.49986875]], dtype=float32)

In [45]:
y_pred[0:10]

array([[0.49227685],
       [0.49445352],
       [0.49694672],
       [0.49949583],
       [0.50203204],
       [0.5045191 ],
       [0.50655574],
       [0.5082141 ],
       [0.5097342 ],
       [0.5108901 ]], dtype=float32)

In [46]:
# Actual value

y_train[0:10]

array([0.9496904 , 0.23664861, 0.44659443, 0.70665635, 0.5998452 ,
       0.06965944, 0.78095975, 0.81462848, 0.14164087, 0.37093653])